name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Construir a imagem de container
      run: echo "executar o docker build"
    - name: Efetuar login no docker hub
      run: echo "executar o docker login"
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: kube-news/src/Dockerfile
        push: true
        tags: |
          carlosmagnogcs/kube-news:${{ github.run_number }}
          carlosmagnogcs/kube-news:latest        
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Autenticar na AWS
      run: echo "Autenticar na AWS"
    - name: Configurar o KubeConfig
      run: echo "Configurar o KubeConfig"
    - name: Aplicar o deploy
      run: echo "Executar o Kubectl apply"
